using Microsoft.EntityFrameworkCore;

namespace EFESMS.Api.Data;

/// <summary>
/// Creates the Operations-module tables without deleting existing data.
/// The app uses EnsureCreated() (which cannot evolve an existing schema), so
/// every Operations table is provisioned here with idempotent DDL mirroring
/// the AppDbContext fluent configuration.
/// </summary>
public static class OpsSchema
{
    private static readonly string[] Statements =
    {
        """
        ALTER TABLE "Users" ADD COLUMN IF NOT EXISTS "AuthVersion" integer NOT NULL DEFAULT 0
        """,
        """
        CREATE TABLE IF NOT EXISTS "Technicians" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "Email" text NULL,
            "Phone" text NULL,
            "Trade" text NOT NULL,
            "Vehicle" text NULL,
            "MaxConcurrentJobs" integer NOT NULL,
            "Available" boolean NOT NULL,
            "Latitude" double precision NULL,
            "Longitude" double precision NULL,
            "Skills" text NULL,
            "Certifications" text NULL,
            "CertificationExpiry" timestamp with time zone NULL,
            "HourlyRate" numeric(18,2) NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "JobCards" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "JobNumber" text NOT NULL,
            "CustomerId" integer NULL,
            "SiteId" integer NULL,
            "EquipmentId" integer NULL,
            "JobType" text NOT NULL,
            "Title" text NOT NULL,
            "Description" text NULL,
            "Status" integer NOT NULL,
            "Priority" integer NOT NULL,
            "AssignedTechnicianId" integer NULL,
            "PlannedStart" timestamp with time zone NULL,
            "PlannedEnd" timestamp with time zone NULL,
            "CompletedAt" timestamp with time zone NULL,
            "EstimatedHours" double precision NULL,
            "RequiredSkills" text NULL,
            "RequiredCertifications" text NULL,
            "Latitude" double precision NULL,
            "Longitude" double precision NULL,
            "QuotedAmount" numeric(18,2) NULL,
            "Notes" text NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            "AgentType" text NULL,
            "AgentAmountKg" double precision NULL,
            "UnitCount" integer NOT NULL DEFAULT 1,
            CONSTRAINT "FK_JobCards_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL,
            CONSTRAINT "FK_JobCards_CustomerSites" FOREIGN KEY ("SiteId") REFERENCES "CustomerSites" ("Id") ON DELETE SET NULL,
            CONSTRAINT "FK_JobCards_Technicians" FOREIGN KEY ("AssignedTechnicianId") REFERENCES "Technicians" ("Id") ON DELETE SET NULL,
            CONSTRAINT "FK_JobCards_OpsEquipment" FOREIGN KEY ("EquipmentId") REFERENCES "OpsEquipment" ("Id") ON DELETE SET NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsEquipment" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "EquipmentNumber" text NOT NULL,
            "CustomerId" integer NULL,
            "SiteId" integer NULL,
            "Name" text NOT NULL,
            "Category" text NOT NULL,
            "Model" text NULL,
            "Make" text NULL,
            "SerialNumber" text NULL,
            "AgentType" text NULL,
            "ManufactureDate" timestamp with time zone NULL,
            "InstallationDate" timestamp with time zone NULL,
            "LastInspectionDate" timestamp with time zone NULL,
            "LastServiceDate" timestamp with time zone NULL,
            "NextServiceDue" timestamp with time zone NULL,
            "ConditionRating" integer NOT NULL,
            "LifeSpanMonths" integer NOT NULL,
            "ServiceIntervalMonths" integer NOT NULL,
            "Status" text NULL,
            "Latitude" double precision NULL,
            "Longitude" double precision NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_OpsEquipment_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL,
            CONSTRAINT "FK_OpsEquipment_CustomerSites" FOREIGN KEY ("SiteId") REFERENCES "CustomerSites" ("Id") ON DELETE SET NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "InventoryItems" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Name" text NOT NULL,
            "Category" text NOT NULL,
            "CurrentStock" integer NOT NULL,
            "ReorderLevel" integer NOT NULL,
            "UnitCost" numeric(18,2) NOT NULL,
            "Unit" text NULL,
            "LeadTimeDays" integer NOT NULL,
            "MonthlyUsage" text NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsInspections" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "JobId" integer NULL,
            "EquipmentId" integer NULL,
            "TechnicianId" integer NULL,
            "CustomerId" integer NULL,
            "SiteId" integer NULL,
            "InspectionDate" timestamp with time zone NOT NULL,
            "Result" text NOT NULL,
            "Cost" numeric(18,2) NOT NULL,
            "Findings" text NULL,
            "NextInspectionDue" timestamp with time zone NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsRefills" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "JobId" integer NULL,
            "EquipmentId" integer NULL,
            "TechnicianId" integer NULL,
            "CustomerId" integer NULL,
            "SiteId" integer NULL,
            "RefillDate" timestamp with time zone NOT NULL,
            "AgentType" text NOT NULL,
            "AgentAmountKg" double precision NOT NULL,
            "Cost" numeric(18,2) NOT NULL,
            "Notes" text NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsMaintenance" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "JobId" integer NULL,
            "EquipmentId" integer NULL,
            "TechnicianId" integer NULL,
            "CustomerId" integer NULL,
            "SiteId" integer NULL,
            "WorkDate" timestamp with time zone NOT NULL,
            "WorkType" text NOT NULL,
            "Cost" numeric(18,2) NOT NULL,
            "Findings" text NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsCertifications" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "TechnicianId" integer NULL,
            "Name" text NOT NULL,
            "ExpiryDate" timestamp with time zone NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsInvoices" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "InvoiceNumber" text NOT NULL,
            "CustomerId" integer NULL,
            "Amount" numeric(18,2) NOT NULL,
            "IssueDate" timestamp with time zone NOT NULL,
            "DueDate" timestamp with time zone NULL,
            "PaidDate" timestamp with time zone NULL,
            "Status" text NOT NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_OpsInvoices_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsQuotations" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "QuotationNumber" text NOT NULL,
            "CustomerId" integer NULL,
            "SiteId" integer NULL,
            "Title" text NOT NULL,
            "QuoteDate" timestamp with time zone NOT NULL,
            "ExpiryDate" timestamp with time zone NOT NULL,
            "DiscountPercent" numeric(5,2) NOT NULL,
            "TaxPercent" numeric(5,2) NOT NULL,
            "Terms" text NULL,
            "Status" text NOT NULL,
            "ConvertedJobId" integer NULL,
            "Notes" text NULL,
            "CreatedAt" timestamp with time zone NOT NULL,
            CONSTRAINT "FK_OpsQuotations_Customers" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("Id") ON DELETE SET NULL,
            CONSTRAINT "FK_OpsQuotations_CustomerSites" FOREIGN KEY ("SiteId") REFERENCES "CustomerSites" ("Id") ON DELETE SET NULL
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsQuotationLines" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "QuotationId" integer NOT NULL,
            "Description" text NOT NULL,
            "Quantity" double precision NOT NULL,
            "UnitPrice" numeric(18,2) NOT NULL,
            "SortOrder" integer NOT NULL,
            CONSTRAINT "FK_OpsQuotationLines_OpsQuotations" FOREIGN KEY ("QuotationId") REFERENCES "OpsQuotations" ("Id") ON DELETE CASCADE
        )
        """,
        """
        CREATE TABLE IF NOT EXISTS "OpsQuotationFiles" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "QuotationId" integer NULL,
            "Name" text NOT NULL,
            "FilePath" text NULL,
            "SizeBytes" bigint NULL,
            "UploadedAt" timestamp with time zone NOT NULL,
            "UploadedBy" text NULL,
            CONSTRAINT "FK_OpsQuotationFiles_OpsQuotations" FOREIGN KEY ("QuotationId") REFERENCES "OpsQuotations" ("Id") ON DELETE CASCADE
        )
        """,
        """
        ALTER TABLE "OpsQuotationFiles" ALTER COLUMN "QuotationId" DROP NOT NULL
        """,
        """
        ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "CustomerName" text NULL
        """,
        """
        CREATE TABLE IF NOT EXISTS "AppSettings" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "Key" text NOT NULL,
            "Value" text NOT NULL,
            "UpdatedAt" timestamp with time zone NOT NULL
        )
        """,
        """
        CREATE UNIQUE INDEX IF NOT EXISTS "IX_AppSettings_Key" ON "AppSettings" ("Key")
        """,
        """
        ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "LastReceivedQty" numeric(18,2) NULL
        """,
        """
        ALTER TABLE "InventoryItems" ADD COLUMN IF NOT EXISTS "LastReceivedDate" timestamp with time zone NULL
        """,
        """
        CREATE TABLE IF NOT EXISTS "StockMovements" (
            "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "InventoryItemId" integer NOT NULL,
            "Type" text NOT NULL,
            "Source" text NOT NULL,
            "Qty" numeric(18,2) NOT NULL,
            "CustomerId" integer NULL,
            "CustomerName" text NULL,
            "JobId" integer NULL,
            "JobNumber" text NULL,
            "Reference" text NULL,
            "Notes" text NULL,
            "MovedBy" text NULL,
            "MovedAt" timestamp with time zone NOT NULL,
            "BalanceAfter" numeric(18,2) NOT NULL,
            CONSTRAINT "FK_StockMovements_InventoryItems" FOREIGN KEY ("InventoryItemId") REFERENCES "InventoryItems" ("Id") ON DELETE CASCADE
        )
        """,
        """
        CREATE INDEX IF NOT EXISTS "IX_StockMovements_InventoryItemId" ON "StockMovements" ("InventoryItemId")
        """,
        """
        ALTER TABLE "StockMovements" ADD COLUMN IF NOT EXISTS "Supplier" text NULL
        """,
        """
        ALTER TABLE "StockMovements" ADD COLUMN IF NOT EXISTS "ReceiptNumber" text NULL
        """,
        """
        ALTER TABLE "StockMovements" ADD COLUMN IF NOT EXISTS "UnitCost" numeric(18,2) NULL
        """,
        """
        ALTER TABLE "StockMovements" ADD COLUMN IF NOT EXISTS "TotalCost" numeric(18,2) NULL
        """,
        """
        ALTER TABLE "StockMovements" ADD COLUMN IF NOT EXISTS "DocumentName" text NULL
        """,
        """
        ALTER TABLE "StockMovements" ADD COLUMN IF NOT EXISTS "DocumentPath" text NULL
        """,
        """
        ALTER TABLE "StockMovements" ADD COLUMN IF NOT EXISTS "DocumentContentType" text NULL
        """,
        """
        ALTER TABLE "StockMovements" ADD COLUMN IF NOT EXISTS "DocumentSizeBytes" bigint NULL
        """,
         """
         ALTER TABLE "JobCards" ADD COLUMN IF NOT EXISTS "Address" text NULL
         """,
         """
         ALTER TABLE "JobCards" ADD COLUMN IF NOT EXISTS "Email" text NULL
         """,
         """
         ALTER TABLE "JobCards" ADD COLUMN IF NOT EXISTS "NextServiceDate" timestamp with time zone NULL
         """,
         """
         ALTER TABLE "JobCards" ADD COLUMN IF NOT EXISTS "WorksDoneSatisfactorily" boolean NOT NULL DEFAULT false
         """,
         """
         ALTER TABLE "JobCards" ADD COLUMN IF NOT EXISTS "AgentType" text NULL
         """,
         """
         ALTER TABLE "JobCards" ADD COLUMN IF NOT EXISTS "AgentAmountKg" double precision NULL
         """,
         """
         ALTER TABLE "JobCards" ADD COLUMN IF NOT EXISTS "UnitCount" integer NOT NULL DEFAULT 1
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "CustomerAddress" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "CustomerVat" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "CustomerTin" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "CustomerContact" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "CustomerEmailSnapshot" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "Currency" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "CompanyVatNo" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "CompanyTinNo" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "BankName" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "BankBranch" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "BankAccountName" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "BankAccountNumber" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "BankAccountNumberZwg" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "DocumentRef" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "PaymentTerms" text NULL
         """,
         """
         ALTER TABLE "OpsQuotations" ADD COLUMN IF NOT EXISTS "ValidityText" text NULL
         """,
         """
         CREATE TABLE IF NOT EXISTS "JobCardTasks" (
             "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             "JobCardId" integer NOT NULL,
             "TaskType" text NOT NULL,
             "EquipmentIds" text NULL,
             "InventoryItemId" integer NULL,
             "Quantity" double precision NOT NULL DEFAULT 1,
             "AgentType" text NULL,
             "UnitType" text NULL,
             "AgentAmountKg" double precision NULL,
             "UnitPrice" numeric(18,2) NULL,
             "IsCompleted" boolean NOT NULL DEFAULT false,
             "Notes" text NULL,
             "SortOrder" integer NOT NULL DEFAULT 0,
             "CreatedAt" timestamp with time zone NOT NULL,
             "AppliedAt" timestamp with time zone NULL,
             CONSTRAINT "FK_JobCardTasks_JobCards" FOREIGN KEY ("JobCardId") REFERENCES "JobCards" ("Id") ON DELETE CASCADE
         )
         """,
         """
         CREATE INDEX IF NOT EXISTS "IX_JobCardTasks_JobCardId" ON "JobCardTasks" ("JobCardId")
         """,
         """
         ALTER TABLE "JobCardTasks" ADD COLUMN IF NOT EXISTS "AppliedAt" timestamp with time zone NULL
         """,
         """
         ALTER TABLE "JobCardTasks" ADD COLUMN IF NOT EXISTS "UnitType" text NULL
         """,
         """
         ALTER TABLE "JobCardTasks" ADD COLUMN IF NOT EXISTS "StoreItemId" integer NULL
         """,
         """
         ALTER TABLE "JobCardTasks" ADD COLUMN IF NOT EXISTS "StoreItemName" text NULL
         """,
         """
         ALTER TABLE "OpsRefills" ADD COLUMN IF NOT EXISTS "Quantity" integer NOT NULL DEFAULT 1
         """,
         """
         ALTER TABLE "OpsMaintenance" ADD COLUMN IF NOT EXISTS "Quantity" integer NOT NULL DEFAULT 1
         """,
         """
         ALTER TABLE "OpsInspections" ADD COLUMN IF NOT EXISTS "Quantity" integer NOT NULL DEFAULT 1
         """,
         """
         ALTER TABLE "OpsRefills" ADD COLUMN IF NOT EXISTS "JobTaskId" integer NULL
         """,
         """
         ALTER TABLE "OpsInspections" ADD COLUMN IF NOT EXISTS "JobTaskId" integer NULL
         """,
         """
         ALTER TABLE "OpsMaintenance" ADD COLUMN IF NOT EXISTS "JobTaskId" integer NULL
         """,
         """
         UPDATE "OpsEquipment"
         SET "ServiceIntervalMonths" = 6,
             "NextServiceDue" = COALESCE("LastServiceDate", "LastInspectionDate", "InstallationDate", "CreatedAt") + INTERVAL '6 months'
         WHERE "Category" ILIKE '%extinguisher%'
         """,
         """
         CREATE TABLE IF NOT EXISTS "StoreItems" (
             "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             "Name" text NOT NULL,
             "Category" text NOT NULL,
             "Unit" text NOT NULL DEFAULT 'unit',
             "CurrentStock" integer NOT NULL DEFAULT 0,
             "UnitCost" numeric(18,2) NOT NULL DEFAULT 0,
             "CreatedAt" timestamp with time zone NOT NULL
         )
         """,
         """
         CREATE TABLE IF NOT EXISTS "StoreMovements" (
             "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
             "StoreItemId" integer NOT NULL,
             "ItemName" text NOT NULL,
             "ItemCategory" text NOT NULL,
             "ItemUnit" text NOT NULL,
             "Type" text NOT NULL,
             "Qty" integer NOT NULL,
             "CustomerId" integer NULL,
             "CustomerName" text NULL,
             "JobId" integer NULL,
             "JobNumber" text NULL,
             "Reference" text NULL,
             "Supplier" text NULL,
             "ReceiptNumber" text NULL,
             "UnitCost" numeric(18,2) NULL,
             "TotalCost" numeric(18,2) NULL,
             "DocumentName" text NULL,
             "DocumentPath" text NULL,
             "DocumentContentType" text NULL,
             "DocumentSizeBytes" bigint NULL,
             "Notes" text NULL,
             "MovedBy" text NULL,
             "MovedAt" timestamp with time zone NOT NULL,
             "BalanceAfter" integer NOT NULL,
             CONSTRAINT "FK_StoreMovements_StoreItems" FOREIGN KEY ("StoreItemId") REFERENCES "StoreItems" ("Id") ON DELETE RESTRICT
         )
         """,
         """
         CREATE UNIQUE INDEX IF NOT EXISTS "IX_StoreItems_Name_Category_Unit" ON "StoreItems" ("Name", "Category", "Unit")
         """,
         """
         CREATE INDEX IF NOT EXISTS "IX_StoreMovements_StoreItemId_MovedAt" ON "StoreMovements" ("StoreItemId", "MovedAt")
         """
    };

    private static readonly string[] Indexes =
    {
        @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_JobCards_JobNumber"" ON ""JobCards"" (""JobNumber"")",
        @"CREATE INDEX IF NOT EXISTS ""IX_OpsEquipment_EquipmentNumber"" ON ""OpsEquipment"" (""EquipmentNumber"")",
        @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_OpsInvoices_InvoiceNumber"" ON ""OpsInvoices"" (""InvoiceNumber"")",
        @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_OpsQuotations_QuotationNumber"" ON ""OpsQuotations"" (""QuotationNumber"")",
    };

    private static readonly string[] Sequences =
    {
        @"CREATE SEQUENCE IF NOT EXISTS ""CustomerNumberSequence"" START WITH 1",
        @"CREATE SEQUENCE IF NOT EXISTS ""JobNumberSequence"" START WITH 1",
        @"CREATE SEQUENCE IF NOT EXISTS ""EquipmentNumberSequence"" START WITH 1",
        @"CREATE SEQUENCE IF NOT EXISTS ""InvoiceNumberSequence"" START WITH 1",
        @"CREATE SEQUENCE IF NOT EXISTS ""QuotationNumberSequence"" START WITH 1",
        @"SELECT setval('""CustomerNumberSequence""', GREATEST(COALESCE((SELECT MAX(CAST(SUBSTRING(""CustomerId"" FROM 5) AS integer)) FROM ""Customers"" WHERE ""CustomerId"" ~ '^CUS-[0-9]+$'), 1), 1), COALESCE((SELECT MAX(CAST(SUBSTRING(""CustomerId"" FROM 5) AS integer)) FROM ""Customers"" WHERE ""CustomerId"" ~ '^CUS-[0-9]+$'), 0) > 0)",
        @"SELECT setval('""JobNumberSequence""', GREATEST(COALESCE((SELECT MAX(CAST(SUBSTRING(""JobNumber"" FROM 5) AS integer)) FROM ""JobCards"" WHERE ""JobNumber"" ~ '^JOB-[0-9]+$'), 1), 1), COALESCE((SELECT MAX(CAST(SUBSTRING(""JobNumber"" FROM 5) AS integer)) FROM ""JobCards"" WHERE ""JobNumber"" ~ '^JOB-[0-9]+$'), 0) > 0)",
        @"SELECT setval('""EquipmentNumberSequence""', GREATEST(COALESCE((SELECT MAX(CAST(SUBSTRING(""EquipmentNumber"" FROM 4) AS integer)) FROM ""OpsEquipment"" WHERE ""EquipmentNumber"" ~ '^EQ-[0-9]+$'), 1), 1), COALESCE((SELECT MAX(CAST(SUBSTRING(""EquipmentNumber"" FROM 4) AS integer)) FROM ""OpsEquipment"" WHERE ""EquipmentNumber"" ~ '^EQ-[0-9]+$'), 0) > 0)",
        @"SELECT setval('""InvoiceNumberSequence""', GREATEST(COALESCE((SELECT MAX(CAST(SUBSTRING(""InvoiceNumber"" FROM 5) AS integer)) FROM ""OpsInvoices"" WHERE ""InvoiceNumber"" ~ '^INV-[0-9]+$'), 1), 1), COALESCE((SELECT MAX(CAST(SUBSTRING(""InvoiceNumber"" FROM 5) AS integer)) FROM ""OpsInvoices"" WHERE ""InvoiceNumber"" ~ '^INV-[0-9]+$'), 0) > 0)",
        @"SELECT setval('""QuotationNumberSequence""', GREATEST(COALESCE((SELECT MAX(CAST(SUBSTRING(""QuotationNumber"" FROM 5) AS integer)) FROM ""OpsQuotations"" WHERE ""QuotationNumber"" ~ '^QUO-[0-9]+$'), 1), 1), COALESCE((SELECT MAX(CAST(SUBSTRING(""QuotationNumber"" FROM 5) AS integer)) FROM ""OpsQuotations"" WHERE ""QuotationNumber"" ~ '^QUO-[0-9]+$'), 0) > 0)",
    };

    public static void Ensure(AppDbContext db)
    {
        foreach (var sql in Statements)
            db.Database.ExecuteSqlRaw(sql);
        foreach (var sql in Indexes)
            db.Database.ExecuteSqlRaw(sql);
        foreach (var sql in Sequences)
            db.Database.ExecuteSqlRaw(sql);
    }
}
