import { useEffect, useState } from 'react'
import {
  Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle,
  Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography,
  useMediaQuery,
} from '@mui/material'
import RefreshIcon from '@mui/icons-material/Refresh'
import PrintIcon from '@mui/icons-material/Print'
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'
import WarningAmberIcon from '@mui/icons-material/WarningAmber'
import { api } from '../api/client'
import type { EngineOutput, Anomaly, ClusteredIncident } from '../types/fireops'
import { SEVERITY_COLORS } from '../types/fireops'
import { useTablePrint } from '../components/print'

export default function AnomaliesPage() {
  const isMobile = useMediaQuery('(max-width: 700px)')
  const [ai, setAi] = useState<EngineOutput | null>(null)
  const [loading, setLoading] = useState(true)
  const [err, setErr] = useState('')
  const [selInc, setSelInc] = useState<Anomaly | null>(null)
  const [selCluster, setSelCluster] = useState<ClusteredIncident | null>(null)
  const printable = useTablePrint()

  const load = async () => {
    setLoading(true)
    setErr('')
    try {
      const a = await api.post<EngineOutput>('/operations/analyze/full', {})
      setAi(a.data)
    } catch (x) { setErr('Failed to run anomaly detection') }
    setLoading(false)
  }

  useEffect(() => { load() }, [])

  const anoms = ai?.anomalies ?? []
  const incidents = ai?.incidents ?? []
  const critical = anoms.filter((x) => x.severity === 'Critical').length

  const refLabel = (a: Anomaly) =>
    a.entityType === 'Equipment' && a.entityId ? `EQ-${String(a.entityId).padStart(6, '0')}` :
    a.entityType === 'Job' && a.entityId ? `JOB-${String(a.entityId).padStart(6, '0')}` :
    a.entityType === 'Invoice' && a.entityId ? `INV-${String(a.entityId).padStart(6, '0')}` :
    a.entityId ? `${a.entityType} #${a.entityId}` : a.entityType

  return (
    <Box>
      <Box sx={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 2, mb: 2 }}>
        <Box sx={{ flexGrow: 1 }}>
          <Typography variant="h4" sx={{ fontWeight: 900, color: '#f2f2f7', letterSpacing: '-0.02em' }}>Anomalies</Typography>
          <Typography variant="body2" sx={{ color: '#9aa0b0' }}>
            {loading ? 'Detecting…' : `${anoms.length} anomalies · ${incidents.length} clusters · ${critical} critical`}
            {ai ? ` · ${ai.ml.clusteringAlgorithm}` : ''}
          </Typography>
        </Box>
        <Button variant="outlined" startIcon={<PrintIcon />} disabled={anoms.length === 0} onClick={() => printable.print({
          title: 'Anomaly Detection Log',
          subtitle: `${anoms.length} anomalies · ${critical} critical · grouped by type`,
          cols: [{ label: 'Type' }, { label: 'Severity' }, { label: 'Description' }, { label: 'Entity' }, { label: 'Value' }, { label: 'Confidence' }],
          rows: anoms.map((a) => [
            a.type,
            a.severity,
            a.description,
            refLabel(a),
            a.detectedValue,
            `${Math.round((a.confidence ?? 0) * 100)}%`,
          ]),
          groupBy: 0,
          note: 'Generated by the anomaly detection engine (unsupervised clustering on operational data).',
        })} sx={{ borderRadius: 2 }}>Print</Button>
        <Button variant="outlined" startIcon={<RefreshIcon />} onClick={load} sx={{ borderRadius: 2 }}>Re-run detection</Button>
      </Box>

      {err && <Alert severity="error" sx={{ mb: 2 }}>{err}</Alert>}
      {critical > 0 && (
        <Alert severity="error" sx={{ mb: 2 }} icon={<WarningAmberIcon />}>
          {critical} critical anomal{critical > 1 ? 'ies' : 'y'} — review immediately (see clusters below).
        </Alert>
      )}

      <Typography variant="h6" sx={{ fontWeight: 800, color: '#f2f2f7', mb: 1.5, fontFamily: 'inherit', letterSpacing: '-0.01em' }}>
        Incident clusters
      </Typography>
      {incidents.length === 0 && (
        <Paper elevation={0} sx={{ border: '1px solid #eef0f4', borderRadius: 2.5, py: 3, px: 2 }}>
          <Typography align="center" sx={{ color: '#9ca3af' }}>No incidents clustered — system is nominal.</Typography>
        </Paper>
      )}
      <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', md: '1fr 1fr' }, gap: 2, mb: 3 }}>
        {incidents.map((inc, i) => {
          const c = SEVERITY_COLORS[inc.severity] ?? '#6b7280'
          return (
            <Paper key={i} elevation={0} onClick={() => setSelCluster(inc)} sx={{ bgcolor: '#ffffff', border: `1px solid ${c}40`, borderLeft: `5px solid ${c}`, borderRadius: 2.5, p: 2.5, cursor: 'pointer', '&:hover': { bgcolor: '#ffe9dd' } }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.75 }}>
                <Chip size="small" icon={<AutoAwesomeIcon sx={{ fontSize: 14 }} />} label={inc.severity} sx={{ bgcolor: `${c}18`, color: c, fontWeight: 800 }} />
                <Chip size="small" label={`${inc.anomalyCount} anomalies`} sx={{ bgcolor: '#f1f5f9', color: '#374151', fontWeight: 700 }} />
              </Box>
              <Typography sx={{ fontWeight: 800, color: '#0f0f13', fontSize: 16 }}>{inc.title}</Typography>
              <Typography variant="body2" sx={{ color: '#6b7280', mt: 0.5 }}>{inc.recommendedAction}</Typography>
              {inc.members.length > 0 && (
                <Box sx={{ mt: 1.5 }}>
                  {inc.members.map((m, j) => (
                    <Box key={j} sx={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 0.5, py: 0.4 }}>
                      <Typography variant="caption" sx={{ fontWeight: 700, color: SEVERITY_COLORS[m.severity] ?? '#6b7280', minWidth: 44 }}>{m.severity}</Typography>
                      <Typography variant="caption" sx={{ color: '#374151', flexGrow: 1 }}>{m.description}</Typography>
                      <Typography variant="caption" sx={{ color: '#9ca3af' }}>{refLabel(m)}</Typography>
                    </Box>
                  ))}
                </Box>
              )}
            </Paper>
          )
        })}
      </Box>

      <Typography variant="h6" sx={{ fontWeight: 800, color: '#f2f2f7', mb: 1.5, fontFamily: 'inherit', letterSpacing: '-0.01em' }}>
        Detection log
      </Typography>
      <TableContainer component={Paper} elevation={0} sx={{ border: '1px solid rgba(255,255,255,0.08)', borderRadius: 2.5, bgcolor: '#ffffff', boxShadow: '0 10px 34px rgba(0,0,0,0.35)' }}>
        <Table size={isMobile ? 'small' : 'medium'}>
          <TableHead>
            <TableRow sx={{ '& th': { bgcolor: '#fafafc', fontWeight: 800, color: '#0f0f13', borderBottom: '1px solid #eef0f4' } }}>
              <TableCell>Type</TableCell>
              <TableCell>Severity</TableCell>
              <TableCell>Description</TableCell>
              {!isMobile && <TableCell>Entity</TableCell>}
              {!isMobile && <TableCell>Value</TableCell>}
              {!isMobile && <TableCell>Confidence</TableCell>}
            </TableRow>
          </TableHead>
          <TableBody>
            {anoms.length === 0 && (
              <TableRow><TableCell colSpan={6} sx={{ textAlign: 'center', color: '#9ca3af', py: 4 }}>No anomalies recorded.</TableCell></TableRow>
            )}
            {anoms.map((a, i) => (
              <TableRow key={i} hover onClick={() => setSelInc(a)} sx={{ cursor: 'pointer', '&:hover': { bgcolor: '#fff3ea' } }}>
                <TableCell><Chip size="small" label={a.type} sx={{ bgcolor: '#f1f5f9', color: '#374151', fontWeight: 700 }} /></TableCell>
                <TableCell><Chip size="small" sx={{ bgcolor: `${SEVERITY_COLORS[a.severity] ?? '#64748B'}18`, color: SEVERITY_COLORS[a.severity] ?? '#64748B', fontWeight: 800 }} label={a.severity} /></TableCell>
                <TableCell><Typography sx={{ fontSize: 14, fontWeight: 600, color: '#0f0f13' }}>{a.description}</Typography></TableCell>
                {!isMobile && <TableCell><Typography variant="caption" sx={{ color: '#6b7280', fontFamily: 'monospace' }}>{refLabel(a)}</Typography></TableCell>}
                {!isMobile && <TableCell><Typography variant="body2" sx={{ fontWeight: 700, color: '#0f0f13' }}>{a.detectedValue}</Typography></TableCell>}
                {!isMobile && <TableCell><Typography variant="caption" sx={{ color: '#9ca3af' }}>{Math.round((a.confidence ?? 0) * 100)}%</Typography></TableCell>}
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>

      <Dialog open={!!selInc} onClose={() => setSelInc(null)} fullWidth maxWidth="sm" fullScreen={isMobile} sx={{ '& .MuiPaper-root': { borderRadius: 3 } }}>
        {selInc && (() => {
          const c = SEVERITY_COLORS[selInc.severity] ?? '#6b7280'
          const line: [string, string][] = [
            ['Type', selInc.type],
            ['Entity', refLabel(selInc)],
            ['Detected value', `${selInc.detectedValue}`],
            ['Recommended action', selInc.recommendedAction ?? '—'],
            ['Confidence', `${Math.round(selInc.confidence * 100)}%`],
          ]
          return (
            <>
              <DialogTitle sx={{ display: 'flex', alignItems: 'center', gap: 1, fontWeight: 800 }}>
                <WarningAmberIcon sx={{ color: c }} /> {selInc.type} anomaly
                <Box sx={{ flexGrow: 1 }} />
                <Chip size="small" sx={{ bgcolor: `${c}18`, color: c, fontWeight: 800 }} label={selInc.severity} />
              </DialogTitle>
              <DialogContent dividers sx={{ bgcolor: '#ffffff' }}>
                <Typography sx={{ fontWeight: 700, color: '#0f0f13', mb: 1.5 }}>{selInc.description}</Typography>
                <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' }, gap: '0 16px' }}>
                  {line.map(([k, v]) => (
                    <Box key={k} sx={{ display: 'flex', justifyContent: 'space-between', gap: 2, py: 0.55, borderBottom: '1px dashed #eef0f4' }}>
                      <Typography variant="caption" sx={{ color: '#6b7280', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.04em' }}>{k}</Typography>
                      <Typography variant="body2" sx={{ color: '#0f0f13', fontWeight: 600, textAlign: 'right' }}>{v}</Typography>
                    </Box>
                  ))}
                </Box>
              </DialogContent>
              <DialogActions sx={{ px: 3, pb: 2 }}>
                <Button onClick={() => setSelInc(null)} sx={{ borderRadius: 2 }}>Close</Button>
              </DialogActions>
            </>
          )
        })()}
      </Dialog>

      <Dialog open={!!selCluster} onClose={() => setSelCluster(null)} fullWidth maxWidth="sm" fullScreen={isMobile} sx={{ '& .MuiPaper-root': { borderRadius: 3, p: 0 }} }>
        {selCluster && (() => {
          const c = SEVERITY_COLORS[selCluster.severity] ?? '#6b7280'
          return (
            <Box sx={{ bgcolor: '#ffffff', p: 3 }}>
              <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 0.75 }}>
                <Chip size="small" icon={<AutoAwesomeIcon sx={{ fontSize: 14 }} />} label={selCluster.severity} sx={{ bgcolor: `${c}18`, color: c, fontWeight: 800 }} />
                <Chip size="small" label={`${selCluster.anomalyCount} anomalies`} sx={{ bgcolor: '#f1f5f9', color: '#374151', fontWeight: 700 }} />
              </Box>
              <Typography sx={{ fontWeight: 800, color: '#0f0f13', fontSize: 17 }}>{selCluster.title}</Typography>
              <Typography variant="body2" sx={{ color: '#374151', mt: 1 }}>{selCluster.recommendedAction}</Typography>
              <Typography variant="subtitle2" sx={{ fontWeight: 800, color: '#0f0f13', mt: 2, mb: 0.75 }}>Members</Typography>
              {selCluster.members.map((m, j) => (
                <Box key={j} onClick={() => setSelInc(m)} sx={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 0.5, py: 0.5, cursor: 'pointer', borderRadius: 1, '&:hover': { bgcolor: '#fff7f2' } }}>
                  <Chip size="small" sx={{ bgcolor: `${SEVERITY_COLORS[m.severity] ?? '#64748B'}18`, color: SEVERITY_COLORS[m.severity] ?? '#64748B', fontWeight: 800, minWidth: 64 }} label={m.severity} />
                  <Typography variant="body2" sx={{ color: '#0f0f13', flexGrow: 1, fontWeight: 600 }}>{m.description}</Typography>
                  <Typography variant="caption" sx={{ color: '#9ca3af', fontFamily: 'monospace' }}>{refLabel(m)}</Typography>
                </Box>
              ))}
              <Box sx={{ display: 'flex', justifyContent: 'flex-end', mt: 2 }}>
                <Button onClick={() => setSelCluster(null)} sx={{ borderRadius: 2 }}>Close</Button>
              </Box>
            </Box>
          )
        })()}
      </Dialog>

      {printable.node}
    </Box>
  )
}
